### ISSUE TITLE
Exception when year above 2099.

### ISSUE THREAD

**Issue by MevlutOzdemir** [voidburn/cron-expression-descriptor#9]
Why is there no support when creating a description for a cron expression when the 'year' is above 2099.

Example:
```CronExpressionDescriptor.getDescription("0 0 0 1 1 ? 2200");```

Exception:
```
it.burning.cron.CronExpressionParser$CronExpressionParseException: The expression describing the YEAR field is not in a valid format. Accepted year values are 1970-2099
	at it.burning.cron.CronExpressionParser.parse(CronExpressionParser.java:497) ~[cron-expression-descriptor-1.2.6.jar:na]
	at it.burning.cron.CronExpressionDescriptor.getDescription(CronExpressionDescriptor.java:212) ~[cron-expression-descriptor-1.2.6.jar:na]
	at it.burning.cron.CronExpressionDescriptor.getDescription(CronExpressionDescriptor.java:871) ~[cron-expression-descriptor-1.2.6.jar:na]
	at it.burning.cron.CronExpressionDescriptor.getDescription(CronExpressionDescriptor.java:860) ~[cron-expression-descriptor-1.2.6.jar:na]
```

**Comment by voidburn** [comment]
That is a configuration option arbitrarily chosen. If your specific use case requires to schedule that far ahead in time, you can embed the two static classes in your project (instead of using this as a dependency), and change the settings here: https://github.com/voidburn/cron-expression-descriptor/blob/master/src/main/java/it/burning/cron/CronExpressionParser.java#L33
